timeout: 5
default_entry: 2

/orion-640x480(tiny)
    protocol: multiboot2
    path: boot():/system/core/orion.ker
    cmdline: rd=0#
    resolution: 640x480x32

    module_path: boot():/boot/ramdisk.img
    module_cmdline: ramdisk

/orion-1024x768(small)
    protocol: multiboot2
    path: boot():/system/core/orion.ker
    cmdline: rd=0#
    resolution: 1024x768x32

    module_path: boot():/boot/ramdisk.img
    module_cmdline: ramdisk

/orion-1920x1080(standard)
    protocol: multiboot2
    path: boot():/system/core/orion.ker
    cmdline: rd=0#
    resolution: 1920x1080x32

    module_path: boot():/boot/ramdisk.img
    module_cmdline: ramdisk

/orion-2560x1440(big)
    protocol: multiboot2
    path: boot():/system/core/orion.ker
    cmdline: rd=0#
    resolution: 2560x1440x32

    module_path: boot():/boot/ramdisk.img
    module_cmdline: ramdisk