timeout: 5

/+orionOS
//  VGA(640x480x32)
protocol: limine
kernel_path: boot():/system/core/kernel
cmdline: a
resolution: 640x480x32
module_path: boot():/boot/ramdisk.img
module_string: ramdisk

//  HD(1280x720x32)
protocol: limine
kernel_path: boot():/system/core/kernel
cmdline: a
resolution: 1280x720x32
module_path: boot():/boot/ramdisk.img
module_string: ramdisk

//  FHD(1920x1080x32)
protocol: limine
kernel_path: boot():/system/core/kernel
cmdline: a
resolution: 1920x1080x32
module_path: boot():/boot/ramdisk.img
module_string: ramdisk

//  QHD(2560x1440x32)
protocol: limine
kernel_path: boot():/system/core/kernel
cmdline: a
resolution: 2560x1440x32
module_path: boot():/boot/ramdisk.img
module_string: ramdisk